#!/bin/bash

# A primitive reminder of where things should go

cp intrusion.service /etc/systemd/system/

#mkdir /etc/intrusion
#cp intrusion.conf /etc/intrusion/
#systemctl enable intrusion
systemctl start intrusion




