#!/bin/bash


cp intrusion.service /etc/systemd/system/
cp intrusion.py /usr/local/bin/
cp readfile_ignore_comments.py /usr/local/bin/
mkdir /etc/intrusion
cp intrusion.conf /etc/intrusion/

chmod +x /usr/local/bin/intrusion.py
systemctl enable intrusion
systemctl start intrusion




